"""Read-only audit of archived runs; write reports only inside the paper directory.

No Isaac imports, simulator execution, or plant/configuration changes.
Run: python scripts/audit_interaction.py
"""
from collections import defaultdict
import csv
import hashlib
import json
import math
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
ROOT = PAPER.parent


def number(value):
    try:
        value = float(value)
        return value if math.isfinite(value) else None
    except (ValueError, TypeError):
        return None


def collect():
    rows, manifest = [], {}
    for hand, prefix in (("robotiq", "iaR"), ("shadow", "iaS")):
        project = ROOT / ("agronomist_" + hand)
        plant = project / "plant.py"
        manifest[str(plant.relative_to(ROOT))] = hashlib.sha256(plant.read_bytes()).hexdigest()
        for run in sorted((project / "outputs").glob(prefix + "*")):
            if not run.is_dir() or not (run / "summary.json").exists():
                continue
            sp, mp = run / "summary.json", run / "run_meta.json"
            if not mp.exists():
                raise ValueError(f"Missing metadata: {run}")
            for source in (sp, mp):
                manifest[str(source.relative_to(ROOT))] = hashlib.sha256(source.read_bytes()).hexdigest()
            summary, meta = json.loads(sp.read_text()), json.loads(mp.read_text())
            for index, leaf in enumerate(summary["leaves"]):
                angle = number(leaf.get("blade_turn_deg"))
                folded = min(angle, 180.0-angle) if angle is not None and 0 <= angle <= 180 else None
                rows.append(dict(hand=hand, run=run.name, attempt=index, leaf=leaf["leaf"],
                    gt_leaf=leaf.get("gt_leaf", ""), outcome=leaf["outcome"],
                    complete=leaf["outcome"] == "complete", fraction=meta.get("pinch_frac"),
                    modulus=meta.get("leaf_youngs"), force_target=meta.get("force_target"),
                    offset_normal=meta.get("offset_normal"), offset_across=meta.get("offset_across"),
                    terminal_turn_raw=angle, terminal_turn_folded=folded,
                    legacy_turn_excluded=folded is not None and folded > 60,
                    sensor_swing=number(leaf.get("sensor_swing_deg")),
                    sensor_turn=number(leaf.get("sensor_turn_deg")),
                    peak_force=number(leaf.get("max_pinch_N"))))
    return rows, manifest


def main():
    rows, manifest = collect()
    out = PAPER / "results"
    out.mkdir(exist_ok=True)
    with (out / "interaction_audit.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    report = ["# Archived interaction audit", "",
        "Generated by `scripts/audit_interaction.py`; no new simulations. Counts are descriptive,",
        "not independent biological replicates. Angles below are TERMINAL patch-normal changes,",
        "not maximum turn, roll-tracking accuracy, slip labels, or presentation success.", "",
        "| hand | runs | attempted leaves | complete | missing sensor swing | folded angle >60 deg |",
        "|---|---:|---:|---:|---:|---:|"]
    for hand in ("robotiq", "shadow"):
        group = [r for r in rows if r["hand"] == hand]
        report.append(f"| {hand} | {len({r['run'] for r in group})} | {len(group)} | "
                      f"{sum(r['complete'] for r in group)} | {sum(r['sensor_swing'] is None for r in group)} | "
                      f"{sum(r['legacy_turn_excluded'] for r in group)} |")
    report += ["", "## Strict fraction × historical-modulus cells", "",
        "Only zero-offset runs with the nominal hand-specific force target (Robotiq 4 N,",
        "Shadow 2 N). The old aggregation also pooled force2 and force6 into the",
        "Robotiq fraction=0.55, E=30000 cell. No new modulus variations are requested.", "",
        "| hand | fraction | E (Pa) | force (N) | attempted | complete |",
        "|---|---:|---:|---:|---:|---:|"]
    cells = defaultdict(list)
    for row in rows:
        nominal = 4 if row["hand"] == "robotiq" else 2
        if row["offset_normal"] == 0 and row["offset_across"] == 0 and row["force_target"] == nominal:
            cells[(row["hand"], row["fraction"], row["modulus"], nominal)].append(row)
    for key, group in sorted(cells.items()):
        report.append("| " + " | ".join(map(str, (*key, len(group), sum(r['complete'] for r in group)))) + " |")
    report += ["", "## Terminal-angle sensitivity among completed attempts", "",
        "This is an audit of a logged endpoint, NOT a new task-success metric. All finite",
        "folded endpoints are retained; high values are flagged, never silently removed.", "",
        "| hand | completed | finite endpoint | endpoint <5 deg | <10 deg | <15 deg |",
        "|---|---:|---:|---:|---:|---:|"]
    for hand in ("robotiq", "shadow"):
        group = [r for r in rows if r["hand"] == hand and r["complete"]]
        angles = [r["terminal_turn_folded"] for r in group if r["terminal_turn_folded"] is not None]
        report.append(f"| {hand} | {len(group)} | {len(angles)} | " +
                      " | ".join(str(sum(a < t for a in angles)) for t in (5, 10, 15)) + " |")
    report += ["", "## Reproduction and provenance", "",
        "`interaction_audit.csv` retains per-attempt metadata, raw/folded endpoints and exclusions.",
        "`interaction_sources.sha256.json` hashes all consumed summaries/metadata and both plant.py files.",
        "Current controller code contains wrist-normal sensing, but a feature existing in today's",
        "code is not evidence that it was logged in an older run. Use the coverage counts above.", ""]
    (out / "interaction_audit.md").write_text("\n".join(report))
    (out / "interaction_sources.sha256.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("\n".join(report))


if __name__ == "__main__":
    main()
